#!/usr/bin/env bash

script_dir=$(cd "$(dirname $BASH_SOURCE[0])"&> /dev/null | pwd)
filter=""
dry="0"

while [[ $# > 0 ]]; do
	if [[ $1 == "--dry" ]]; then 
		dry="1"
	else
		filter=$1
	fi

	shift
done

log() {
	if [[ $dry == "1" ]]; then 
		echo "[DRY] $@"
	else 
		echo "$@"
	fi
}

execute() {
	log "Execute $@"

	if [[ $dry == "1" ]]; then 
		return
	fi

	"$@"
}


cd $script_dir
scripts=$(find ./runs -mindepth 1 -maxdepth 1 -executable -type f )

for script in $scripts; do
	if echo "$script" | grep -qv "$filter"; then
		log "Filtered $script!"
		continue
	fi

	execute $script
done

